### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by vespakoen** [feature-ninja/testing-matrix#5]
looks like MSTest's DataRow :)

https://www.mmp.dev/articles/2019-11-09-DynamicData/

**Comment by rojtjo** [comment]
That actually looks more like the `#[TestWith([1, 2, 3], 'my-test')]` attribute of PHPUnit:
https://docs.phpunit.de/en/10.5/attributes.html#testwith

This library is more intended to generate all possible combinations to test :rocket:
